---
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=null
        exclude: docs/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        args:
          - --fix
          - --ignore=D401,D404,D203,D213
          - --select=E4,E7,E9,F,I,D
          - --per-file-ignores=__init__.py:F401
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ["pyright"]
        args:
          - --project=pyproject.toml
          - --reportMissingImports=none
